### ISSUE TITLE
Support for slicing in DottedList

### ISSUE THREAD

**Issue by ryanwitt** [carlosescri/DottedDict#7]
Looks like DottedList does not support slicing:

``` python
>>> from dotted.collection import DottedCollection
>>> c = DottedCollection.factory(
        {'content': {'comments': ["hi there", "cool site", "no way", "first"]}})
>>> c['content.comments'][:2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dotted/collection.py", line 174, in __getitem__
    raise IndexError('cannot get %s in %s' % (index, repr(self.store)))
IndexError: cannot get slice(None, 2, None) in ['hi there', 'cool site', 'no way', 'first']
```

This is kinda a bummer, since lots of code uses slicing. But should be pretty easy to add. Working on patch.

**Comment by ryanwitt** [comment]
Pull request: https://github.com/carlosescri/DottedDict/pull/8

**Comment by carlosescri** [comment]
Great! Thank you @ryanwitt.
